### ISSUE TITLE
新建课程开始和结束时间是否需要格式

### ISSUE THREAD

**Issue by GuiyuChi** [Librazy/ControllerWorkingGroup-Public#10]
![image](https://user-images.githubusercontent.com/18232545/33425352-6ecc9a80-d5f9-11e7-948e-61a09d9ab704.png)

json中为
"startTime":"2017-09-20"

**Comment by Librazy** [comment]
这个在HTML页面上应该是

``` html
<input type="date">

```

这个标签的数据格式是YYYY-MM-DD

**Comment by Librazy** [comment]
https://w3c.github.io/html-reference/input.date.html#input.date.attrs.value
