### ISSUE TITLE
StudentMainUI 小程序端获取与用户相关的课程列表的API修改建议

### ISSUE THREAD

**Issue by xmusoftware15** [Librazy/ControllerWorkingGroup-Public#15]
StudentMainUI这边拿course信息是，返回的json里面我觉得可以加个teachername。

**Comment by Librazy** [comment]
相关问题：https://github.com/Librazy/ControllerWorkingGroup-Public/issues/25

**Comment by Librazy** [comment]
https://app.swaggerhub.com/apis/liqueurlibrazy/classmanagementsystem/1.0.0-beta.3#/class/getClass
