### ISSUE TITLE
8.课程内页--周三1-2节修改 里面的time不知道是干什么用的

### ISSUE THREAD

**Issue by GuiyuChi** [Librazy/ControllerWorkingGroup-Public#18]
![_x 0b09j vmv n 88iyiu](https://user-images.githubusercontent.com/18232545/33441318-617bfeb4-d62d-11e7-9ac8-5a46ead4ac53.png)

**Comment by Librazy** [comment]
看起来URL应该是 `PUT /class/{classId}`  
这里原意是表示12节。  
在下一个版本中根据邱老师的建议上课时间会改为一个字符串。
