### ISSUE TITLE
小程序打分（GradePresentationUI、GradePresentationEndUI）页面，get 和 put 的信息都不全

### ISSUE THREAD

**Issue by wayne-liberty** [Librazy/ControllerWorkingGroup-Public#27]
get 的时候只拿到id，不知道 是a1 还是 b2
put 的时候没有指明 group id

**Comment by wayne-liberty** [comment]
还有一点，打分的时候不能打自己的组，所以get 的时候是传入自己的 groupId 来得到可以打分的组，还是说自己根据自己的groupId 来判断呢

**Comment by Librazy** [comment]
put的时候URL中指定了被打分的组。
Get的问题会修改，加一个name。

**Comment by ddancn** [comment]
已修，感谢指正

**Comment by wayne-liberty** [comment]
{
    "presentationGrade": [
    {
        "topicId": 257,
        "grade": 4
    },
    {
        "topicId": 258,
        "grade": 5
    }
    ]
}

这个打分发送的数据，是groupId 写成 topicId 了么？

**Comment by ddancn** [comment]
大概是因为一个组可以选多个话题吧，设定是给话题评分，而不是给小组。
