### ISSUE TITLE
小程序Teacher:3，4：关于class的calling以及course下添加currentSeminar

### ISSUE THREAD

**Issue by caistrong** [Librazy/ControllerWorkingGroup-Public#33]
在小程序Teacher的ClassManage界面下：需要一个日期 11月6日-11月12日 以及groupMethod这两个数据，
这两个数据需要知道currentSeminar,而目前只有返回某个course的seminarArray的API是需要自己在前端根据当前的时间来从seminarArray里找出currentSeminar吗？

**Comment by caistrong** [comment]
将class下的calling字段的值变为当前的seminarId的话，那原本的教师开始签到的时候put到 /class/{classId}的请求数据{"calling":true}应该改成什么？

**Comment by Librazy** [comment]
预计会加一个VO

**Comment by Librazy** [comment]
PUT也相应改为 `{"calling": seminarId}` 如 `{"calling": 10}` ，结束为 PUT `{"calling": -1}`

**Comment by caistrong** [comment]
好的 我明白了 辛苦了

**Comment by Librazy** [comment]
https://github.com/Librazy/ControllerWorkingGroup-Public/issues/31#issuecomment-348698966
