### ISSUE TITLE
PUT /class/{classId}/attendance/{studentId} 签到功能是有返回数据的，用以改变页面状态

### ISSUE THREAD

**Issue by bebory** [Librazy/ControllerWorkingGroup-Public#37]
按wxml界面来看，至少返回一个int 数据，为1表示成功，2表示迟到签到成功。个人建议加上一个3，表示签到失败。

**Comment by Librazy** [comment]
下个版本根据邱老师的建议对URL做了一些修改 [PUT `/seminar/{seminarId}/class/{classId}/attendance/{studentId}`](https://app.swaggerhub.com/apis/liqueurlibrazy/classmanagementsystem/1.0.0-beta.3#/seminar/updateAttendance)
签到失败是返回400错误，现在确实没有区分签到成功和迟到签到成功是个问题

**Comment by Librazy** [comment]
下一个版本已经修改了 https://app.swaggerhub.com/apis/liqueurlibrazy/classmanagementsystem/1.0.0-beta.3#/seminar/updateAttendance
