### ISSUE TITLE
这条api下面输入和输出的topic不对应

### ISSUE THREAD

**Issue by GuiyuChi** [Librazy/ControllerWorkingGroup-Public#39]
![hqky18 u hfmwcya29 tqa](https://user-images.githubusercontent.com/18232545/33514732-00f69bd6-d794-11e7-9468-ab16d9e3c998.png)

**Comment by Librazy** [comment]
emm举例子的时候手滑了，意思知道就好了（

**Comment by GuiyuChi** [comment]
然而检验的时候会出问题吗？

**Comment by Librazy** [comment]
测试的时候我们不关心具体数据，只关心结构
