### ISSUE TITLE
通过学号和seminarId去获得groupId 再通过groupId去获得grade

### ISSUE THREAD

**Issue by 24320152202743** [Librazy/ControllerWorkingGroup-Public#43]
通过学号和seminarId去获得groupId 再通过groupId去获得grade 这样的办法太麻烦了，如果group的表中含有seminarid classid 以及这个组底下的studentid 那么只要通过studentid就可以获得groupid了 不用形如：GET /seminar/{seminarId}/group?include={studentId} 获取小组 {groupId}（摘抄自controller标准组）否则会发很多次请求吧

**Comment by Librazy** [comment]
相关 #42 
下一个版本会添加这个，获取自身所在小组 https://app.swaggerhub.com/apis/liqueurlibrazy/classmanagementsystem/1.0.0-beta.3#/seminar/getStudentGroupBySeminarId
