### ISSUE TITLE
随机分组时无法获得小组选择的topic

### ISSUE THREAD

**Issue by GuiyuChi** [Librazy/ControllerWorkingGroup-Public#46]

**Comment by GuiyuChi** [comment]
组号也无法获得，界面要求填写1-A-1这样

**Comment by Librazy** [comment]
[/seminar/{seminarId}/group/my](https://app.swaggerhub.com/apis/liqueurlibrazy/classmanagementsystem/1.0.0-beta.3#/seminar/getStudentGroupBySeminarId)
