### ISSUE TITLE
/group/{groupId}/grade  按ID获取小组的讨论课成绩 无法得到课堂讨论得分和报告得分

### ISSUE THREAD

**Issue by GuiyuChi** [Librazy/ControllerWorkingGroup-Public#47]

**Comment by Librazy** [comment]
emm有啊

**Comment by GuiyuChi** [comment]
![m8u4 c 7rdhuqu wgj yitw](https://user-images.githubusercontent.com/18232545/33523067-3f469e8c-d838-11e7-86d9-c3e1e816750b.png)

**Comment by GuiyuChi** [comment]
以前的报告分呢？还有grade是总分还是课堂学生评分

**Comment by Librazy** [comment]
group是属于某个seminar的，分数是本节讨论课的分数，学生评分是presentationGrade，教师评分是reportGrade，根据评分标准得到总分grade
