### ISSUE TITLE
属性命名问题

### ISSUE THREAD

**Issue by MengJiapeng** [Librazy/ControllerWorkingGroup-Public#5]
在`PUT /course/{courseId}`中，Request Body中的传输的数据为：  
```
{
    "name": "OOAD",
    "description": "面向对象分析与设计",
    "startTime": "2017-09-20",
    "endTime": "2018-1-1",
    "proportions": {
        "3": 20,
        "4": 60,
        "5": 20,
        "report": 70,
        "presentation": 30
    }
}
```
`3`作为`properties`的属性，不应该以数字来命名，这样无论是要映射到Java对象，还是js解析数据都会无法进行。

**Comment by Librazy** [comment]
https://app.swaggerhub.com/apis/liqueurlibrazy/classmanagementsystem/1.0.0-beta.3
在下一个版本中 `3` `4` `5` 会被对应替换为 `c` `b` `a`
